site_name: Hypercubing Developers
site_url: https://dev.hypercubing.xyz/
docs_dir: docs/
repo_name: Hypercubers/dev.hypercubing.xyz
repo_url: https://github.com/Hypercubers/dev.hypercubing.xyz
edit_uri: edit/main/docs/
theme:
  name: material
  favicon: assets/images/favicon.png
  logo: assets/images/logo.svg
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.action.edit
    - content.code.copy
    - navigation.footer
    - navigation.instant
    - navigation.sections
    - navigation.top
    - navigation.path
  icon:
    edit: material/pencil
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Hypercubers
    - icon: fontawesome/brands/discord
      link: https://discord.gg/3hVSe8rDKa
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - footnotes
  - pymdownx.caret
  - pymdownx.tilde
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.toc:
      permalink: true
  - md_in_html
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.keys
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.superfences:
      custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - pymdownx.arithmatex:
      generic: true
nav:
  - Welcome: index.md
  - Prerequisites: prereqs.md
  - Hyperspeedcube:
    - Puzzle Development:
      - 1. Introduction: hsc/puzzle-dev/index.md
      - 2. Puzzle Geometry: hsc/puzzle-dev/geometry.md
      - 3. First Steps: hsc/puzzle-dev/first-puzzle.md
    - Internals:
      - 1. Introduction: hsc/internals/index.md
      - 2. Vectorspace GA: hsc/internals/vga.md
      - 3. Projective GA: hsc/internals/pga.md
      - 4. Conformal GA: hsc/internals/cga.md
      - 5. Slicing: hsc/internals/slicing.md
    - Lua API Reference:
      - hsc/lua/basics.md
      - hsc/lua/blades.md
      - hsc/lua/transforms.md
      - hsc/lua/symmetries.md
      - hsc/lua/orbits.md
      - hsc/lua/puzzle-construction.md
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
plugins:
  - search
  - glightbox
validation:
  absolute_links: relative_to_docs
  anchors: warn
  unrecognized_links: warn
